from agents.base import AgentResult, BaseAgent
from agents.roles import CODER


class CoderAgent(BaseAgent):
    def __init__(self):
        super().__init__(CODER)

    def code(self, task: str, plan: str, memory_context: str = "") -> AgentResult:
        mem = f"\n\n{memory_context}\n" if memory_context else ""
        user = f"""## Original task

{task}

## Plan from Planner (Ava)

{plan}
{mem}
Implement the solution as Python code now. Stay consistent with shared memory decisions."""
        return self.run(user)

    def _run_offline(self, user_message: str) -> str:
        task_line = "feature"
        for line in user_message.splitlines():
            if line.strip() and not line.startswith("#"):
                task_line = line.strip()[:80]
                break
        if "## Original task" in user_message:
            body = user_message.split("## Original task", 1)[1]
            body = body.split("## Plan", 1)[0].strip()
            task_line = body.splitlines()[0][:80] if body else task_line

        safe = task_line.replace('"', "'")
        return f'''```python
"""Generated by Rex (Software Engineer) — offline mode."""
from __future__ import annotations

from pydantic import BaseModel, Field


class RequestModel(BaseModel):
    """Input for: {safe}"""
    payload: str = Field(..., min_length=1)


class ResponseModel(BaseModel):
    ok: bool = True
    message: str
    task: str


def handle(req: RequestModel) -> ResponseModel:
    """Core logic sketched for the assigned task."""
    return ResponseModel(
        ok=True,
        message="processed",
        task="{safe}",
    )


# FastAPI wiring example:
# from fastapi import APIRouter
# router = APIRouter()
# @router.post("/run", response_model=ResponseModel)
# async def endpoint(body: RequestModel) -> ResponseModel:
#     return handle(body)
```
'''


coder_agent = CoderAgent()
